// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo4.common.protobuf;

public interface MessageWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:MessageWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Any message = 2;</code>
   * @return Whether the message field is set.
   */
  boolean hasMessage();
  /**
   * <code>.google.protobuf.Any message = 2;</code>
   * @return The message.
   */
  com.google.protobuf.Any getMessage();
  /**
   * <code>.google.protobuf.Any message = 2;</code>
   */
  com.google.protobuf.AnyOrBuilder getMessageOrBuilder();
}
