// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo4.common.protobuf;

public interface ServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServerResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ServerResponse.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.ServerResponse.Status status = 1;</code>
   * @return The status.
   */
  com.mdevv.tpo4.common.protobuf.ServerResponse.Status getStatus();

  /**
   * <code>repeated string content = 2;</code>
   * @return A list containing the content.
   */
  java.util.List<java.lang.String>
      getContentList();
  /**
   * <code>repeated string content = 2;</code>
   * @return The count of content.
   */
  int getContentCount();
  /**
   * <code>repeated string content = 2;</code>
   * @param index The index of the element to return.
   * @return The content at the given index.
   */
  java.lang.String getContent(int index);
  /**
   * <code>repeated string content = 2;</code>
   * @param index The index of the value to return.
   * @return The bytes of the content at the given index.
   */
  com.google.protobuf.ByteString
      getContentBytes(int index);
}
