// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo4.common.protobuf;

public interface SubscriberMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubscriberMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.SubscriberMessage.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.SubscriberMessage.Type type = 1;</code>
   * @return The type.
   */
  com.mdevv.tpo4.common.protobuf.SubscriberMessage.Type getType();

  /**
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();
}
