// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Communication.proto

package com.mdevv.tpo4.common.protobuf;

public interface UpdateMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UpdateMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UpdateMessage.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.UpdateMessage.Type type = 1;</code>
   * @return The type.
   */
  com.mdevv.tpo4.common.protobuf.UpdateMessage.Type getType();

  /**
   * <code>string topic = 2;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 2;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
